name: GENREEL

on:
  schedule:
    - cron: '0 17 * * *'  # Runs at 5 PM UTC daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.4'
          
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg
          
      - name: Install Requirements
        run: |
          pip install -r final.txt

      # Step 2: Debug yt-dlp command
      - name: Debug yt-dlp
        run: |
          yt-dlp -v -o "/home/runner/work/Short-Video-Auto-Generation/Short-Video-Auto-Generation/output/video_480_852_" https://www.reddit.com/r/FunnyDogVideos/comments/17oz095/dogs_eye_expressions/
          
      - name: Run Script
        run: python src/main.py
